# Generated by Django 5.0.7 on 2024-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.CharField(max_length=50)),
                ('Ename', models.CharField(max_length=50)),
                ('sal', models.CharField(max_length=50)),
                ('deptno', models.CharField(max_length=50)),
            ],
        ),
    ]
